ansible
azure-identity
azure-core
azure-mgmt-resource<24.0.0
azure-mgmt-network<30.0.0
azure-mgmt-compute<36.0.0
azure-mgmt-dns
azure-mgmt-managementgroups
azure-mgmt-marketplaceordering
azure-mgmt-authorization
azure-mgmt-monitor
azure-mgmt-storage
azure-mgmt-keyvault
azure-mgmt-msi
azure-mgmt-privatedns
azure-mgmt-containerservice
azure-mgmt-web
azure-mgmt-sql
azure-mgmt-rdbms
azure-mgmt-trafficmanager
azure-mgmt-redis
azure-mgmt-cosmosdb
azure-mgmt-servicebus
azure-storage-blob
azure-storage-common
msrest
msrestazure