#SPDX-License-Identifier: MIT-0
---
# tasks file for az-vm


- name: Create Resource Group
  include_tasks: rg.yml

- name: Setup Network
  include_tasks: network.yml

- name: Create VM
  include_tasks: vm.yml

